# -*- coding: utf-8 -*-
{
    "name": "Inventory Fireman",
    "summary": "UO, véhicules, personnel et abonnements de l'application d'inventaire des pompiers, synchronisés avec Firebase",
    "category": "Operations/Inventory",
    "author": "ZappOne",
    "version": "18.0.2.0.0",
    "website": "https://www.open-net.ch",
    "license": "OPL-1",
    "depends": [
        "base",
        "mail",
        "portal",
        "website",
        "sale_management",
        "sale_subscription",
        "account",
        "account_payment",
        "payment_custom",
        "helpdesk",
    ],
    "external_dependencies": {"python": ["firebase_admin"]},
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/fireman_data.xml",
        "data/ir_cron.xml",
        "views/fireman_views.xml",
        "views/fireman_config_views.xml",
        "views/report_uo_inventory.xml",
        "views/portal_uo.xml",
        "views/portal_auth.xml",
        "views/portal_contact.xml",
        "views/portal_policies.xml",
        "views/portal_breadcrumbs.xml",
        "views/website_pricing.xml",
        "views/home_page_new.xml",
        "views/website_menu.xml",
        "views/website_footer.xml",
        "views/website_customizations.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "inventory_fireman/static/src/css/custom_portal.css",
            "inventory_fireman/static/src/css/portal_custom.css",
        ],
    },
    "installable": True,
    "application": True,
}
